config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'

  get 'filtered_search/games', to: 'games#filtered_search', as: 'filtered_search_games'
  get 'users/:user_id/library', to: 'user_games#index', as: :user_library
  get 'user_games/:user_id/edit', to: 'user_games#edit'
  resources :promotions
  resources :games
  
  resources :platforms
  resources :developers
  resources :publishers
  resources :genres
  devise_for :users
  resources :users do
    resources :friend_requests, only: [:create, :destroy, :show] do
      member do
        put :accept
      end
    end
    member do
      get 'friends'
    end
  end
  resources :friendships, only: [:create, :destroy]
  resources :reviews
  resources :collections do
    delete 'games/:id', to: 'collections#remove_game', as: :remove_game
  end 
  resources :user_games, only: [:create, :edit, :update]
  resources :games do
    resources :user_games, only: [:create, :edit, :update]
    member do
      post 'wishlist'
      post 'favorite'
      post :add_to_collection
    end
      post 'create_review', on: :member
  end
  get 'admin', to: 'admin#index'
  namespace :admin do
    resources :users
  end
  authenticate :user, ->(user) { user.is_admin? } do
    namespace :admin do
      root to: "users#index"
    end
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/collection.rb
class Collection < ApplicationRecord
  belongs_to :user
  has_many :collection_items, dependent: :destroy
  has_many :games, through: :collection_items
end

app/controllers/collections_controller.rb
class CollectionsController < ApplicationController
        before_action :authenticate_user!
        before_action :set_collection, only: [:show, :edit, :update, :destroy]
      
        def index
          @collections = current_user.collections
        end
      
        def show
        end
      
        def new
          @collection = Collection.new
        end
      
        def create
          @collection = current_user.collections.build(collection_params)
      
          if @collection.save
            redirect_to @collection, notice: 'Collection was successfully created.'
          else
            render :new
          end
        end
      
        def edit
        end
      
        def update
          if @collection.update(collection_params)
            redirect_to @collection, notice: 'Collection was successfully updated.'
          else
            render :edit
          end
        end

        def destroy
          @collection = Collection.find(params[:id])
          
          if @collection.user_id == current_user.id
            @collection.destroy
            redirect_to user_path(current_user), notice: "Coleção excluída com sucesso!"
          else
            redirect_to user_path(@current_user), alert: "Você não tem permissão para excluir esta coleção."
          end
        end

        def remove_game
          @collection = Collection.find(params[:collection_id])
          @game = Game.find(params[:id])
          @collection.games.delete(@game)
          redirect_to @collection, notice: 'Jogo removido da coleção com sucesso!'
        end
      
        private
      
        def set_collection
          @collection = Collection.find(params[:id])
        end
      
        def collection_params
          params.require(:collection).permit(:title, game_ids: [])
        end
end

app/helpers/collections_helper.rb
module CollectionsHelper
end

app/views/collections/new.html.erb
<%= simple_form_for @collection do |f| %>
  <%= f.input :title %>
  <%= f.button :submit, 'Create Collection' %>
<% end %>

<%= link_to "Back", user_path(current_user), class: 'btn btn-primary' %>

app/views/collections/show.html.erb
<h1><%= @collection.title %></h1>

<% if @collection.games.any? %>
  <ul>
    <% @collection.games.each do |game| %>
        <li>
          <%= link_to game.name_game, game_path(game) %>
          <% if current_user == @collection.user %>
            <%= button_to 'Remover', collection_remove_game_path(@collection, game), method: :delete %>
          <% end %>
      </li>
    <% end %>
  <% elsif current_user == @collection.user %>
    <p>Você ainda não adicionou jogos à coleção.</p>
  <% else %>
    <p>Este usuário ainda não adicionou jogos à coleção.</p>
<% end %>
</ul>

<% if @collection.user == current_user %>
  <%= button_to 'Excluir Coleção', collection_path, method: :delete, class: 'btn btn-outline-danger' %></p>
<% end %>

<%= link_to "Back", user_path(@collection.user), class: 'btn btn-primary' %>