config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'

  get 'filtered_search/games', to: 'games#filtered_search', as: 'filtered_search_games'
  get 'users/:user_id/library', to: 'user_games#index', as: :user_library
  get 'user_games/:user_id/edit', to: 'user_games#edit'
  resources :promotions
  resources :games
  
  resources :platforms
  resources :developers
  resources :publishers
  resources :genres
  devise_for :users
  resources :users do
    resources :friend_requests, only: [:create, :destroy, :show] do
      member do
        put :accept
      end
    end
    member do
      get 'friends'
    end
  end
  resources :friendships, only: [:create, :destroy]
  resources :reviews
  resources :collections do
    delete 'games/:id', to: 'collections#remove_game', as: :remove_game
  end 
  resources :user_games, only: [:create, :edit, :update]
  resources :games do
    resources :user_games, only: [:create, :edit, :update]
    member do
      post 'wishlist'
      post 'favorite'
      post :add_to_collection
    end
      post 'create_review', on: :member
  end
  get 'admin', to: 'admin#index'
  namespace :admin do
    resources :users
  end
  authenticate :user, ->(user) { user.is_admin? } do
    namespace :admin do
      root to: "users#index"
    end
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/collection.rb
class Collection < ApplicationRecord
  belongs_to :user
  has_many :collection_items, dependent: :destroy
  has_many :games, through: :collection_items
end

app/models/developer.rb
class Developer < ApplicationRecord
    validates :name_developer, :description_developer, presence: true
    has_many :games
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :game
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :user
  belongs_to :friend, class_name: 'User'

  validates :friend_id, uniqueness: { scope: :user_id }

  def self.create_from_request(request)
    create(user_id: request.user_id, friend_id: request.friend_id, status: 'aceito')
  end

  def remove_friendship
    user.friends.destroy(friend)
    friend.friends.destroy(user)
    destroy
  end
  
end

app/models/game.rb
class Game < ApplicationRecord
    validates :name_game, :description_game, presence: true
    validates :rate_game, numericality: { greater_than_or_equal_to: 0.0, less_than_or_equal_to: 10.0 }
    has_one_attached :icon
    
    belongs_to :publisher
    has_and_belongs_to_many :genres, join_table: :game_genres
    accepts_nested_attributes_for :genres
    has_many :promotion_games
    has_many :promotions, through: :promotion_games
    has_and_belongs_to_many :platforms, join_table: :game_platforms
    accepts_nested_attributes_for :platforms
    belongs_to :developer
    has_many :reviews, dependent: :destroy
    has_many :favorites, dependent: :destroy
    has_many :favorited_by, through: :favorites, source: :user
    has_many :collection_items, dependent: :destroy
    has_many :collections, through: :collection_items
    has_many :wishlists, dependent: :destroy
    has_many :wishlisted_by, through: :wishlists, source: :user
    has_many :user_games, dependent: :destroy
    has_many :users, through: :user_games

    def calculate_average_rating
        reviews.average(:score).to_f.round(1)
      end
      
end

app/models/game_genre.rb
class GameGenre < ApplicationRecord
  belongs_to :game
  belongs_to :genre
end

app/models/genre.rb
class Genre < ApplicationRecord
    validates :name_genre, :description_genre, presence: true
    has_and_belongs_to_many :games, join_table: :game_genres
    #has_many :games, through: :game_genres
end

app/models/platform.rb
class Platform < ApplicationRecord
    validates :name_platform, :description_platform, presence: true
    has_and_belongs_to_many :games, join_table: :game_platforms
    #has_many :games, through: :game_platforms
end

app/models/promotion.rb
class Promotion < ApplicationRecord
  belongs_to :game
  has_many :promotion_games
  has_many :games, through: :promotion_games
  has_many :user_promotions
  has_many :users, through: :user_promotions
  validates :title, :description, :start_date, :end_date, presence: true
  validate :end_date_is_after_start_date

  private
  def end_date_is_after_start_date
    return if end_date.blank? || start_date.blank?

    if end_date < start_date
      errors.add(:end_date, "deve ser maior que a data inicial.")
    end
  end

end

app/models/publisher.rb
class Publisher < ApplicationRecord
    validates :name_publisher, :description_publisher, presence: true
    has_many :games
end

app/models/review.rb
class Review < ApplicationRecord
  validates :score, numericality: { greater_than_or_equal_to: 0.0, less_than_or_equal_to: 10.0 }
  validates :user_id, uniqueness: { scope: :game_id }
  belongs_to :game
  belongs_to :user
end

app/models/shop.rb
class Shop < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  validates :nickname, :description, presence: true
  has_many :user_promotions
  has_many :collections, dependent: :destroy
  has_many :promotions, through: :user_promotions
  has_many :reviews
  has_many :favorites, dependent: :destroy
  has_many :favorite_games, through: :favorites, source: :game
  has_many :wishlists, dependent: :destroy
  has_many :wishlist_games, through: :wishlists, source: :game
  has_many :user_games, dependent: :destroy
  has_many :games, through: :user_games
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  enum role: [:user, :admin]

  has_many :friendships, dependent: :destroy
  has_many :friends, through: :friendships
  has_many :inverse_friendships, class_name: 'Friendship', foreign_key: 'friend_id', dependent: :destroy
  has_many :inverse_friends, through: :inverse_friendships, source: :user    
  
  has_many :sent_friend_requests, class_name: 'FriendRequest', foreign_key: 'requester_id', dependent: :destroy
  has_many :received_friend_requests, class_name: 'FriendRequest', foreign_key: 'receiver_id', dependent: :destroy

  def friendship_with(other_user)
    Friendship.find_by(user: self, friend: other_user) || Friendship.find_by(user: other_user, friend: self)
  end
  
  def recommended_games
    friend_ids = friendships.pluck(:friend_id)
    friend_favorite_game_ids = Favorite.where(user_id: friend_ids).pluck(:game_id)
    excluded_game_ids = game_ids + favorite_games.pluck(:id)
    Game.where(id: friend_favorite_game_ids).where.not(id: excluded_game_ids + user_games.pluck(:game_id))
  end

  def is_admin?
    self.admin
  end

end

app/models/user_game.rb
class UserGame < ApplicationRecord
  validates :user, :game, presence: true
  validates :game_id, uniqueness: { scope: :user_id }
  belongs_to :user
  belongs_to :game
  enum status: [:played, :playing, :unfinished]
end

app/models/wishlist.rb
class Wishlist < ApplicationRecord
  belongs_to :user
  belongs_to :game
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/index.html.erb
<h1>Admin Config</h1>
<h2>Jogos</h2>

<%= link_to 'Criar novo jogo', new_game_path, class: 'btn btn-primary mb-3' %>

<table class="table">
  <thead class="thead-dark">
    <tr>
      <th scope="col">Nome</th>
      <th scope="col">Descrição</th>
      <th scope="col">Classificação</th>
      <th scope="col">Ação</th>
    </tr>
  </thead>

  <tbody>
    <% @games.each do |game| %>
      <tr>
        <td><%= game.name_game %></td>
        <td><%= game.description_game %></td>
        <td><%= game.rate_game %></td>
        <td>
          <%= link_to 'Visualizar', game, class: 'btn btn-secondary mr-2' %>
          <%= link_to 'Editar', edit_game_path(game), class: 'btn btn-info mr-2' %>
          <%= link_to 'Excluir', game, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>

<h2>Plataformas</h2>

<%= link_to 'Criar nova plataforma', new_platform_path, class: 'btn btn-primary mb-3' %>

<table class="table">
  <thead class="thead-dark">
    <tr>
      <th scope="col">Nome</th>
      <th scope="col">Descrição</th>
      <th scope="col">Ação</th>
    </tr>
  </thead>

  <tbody>
    <% @platforms.each do |platform| %>
      <tr>
        <td><%= platform.name_platform %></td>
        <td><%= platform.description_platform %></td>
        <td>
          <%= link_to 'Visualizar', platform, class: 'btn btn-secondary mr-2' %>
          <%= link_to 'Editar', edit_platform_path(platform), class: 'btn btn-info mr-2' %>
          <%= link_to 'Excluir', platform, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>

<h2>Desenvolvedores</h2>

<%= link_to 'Criar novo desenvolvedor', new_developer_path, class: 'btn btn-primary mb-3' %>

<table class="table">
  <thead class="thead-dark">
    <tr>
      <th scope="col">Nome</th>
      <th scope="col">Descrição</th>
      <th scope="col">Ação</th>
    </tr>
  </thead>

  <tbody>
    <% @developers.each do |developer| %>
      <tr>
        <td><%= developer.name_developer %></td>
        <td><%= developer.description_developer %></td>
        <td>
          <%= link_to 'Visualizar', developer, class: 'btn btn-secondary mr-2' %>
          <%= link_to 'Editar', edit_developer_path(developer), class: 'btn btn-info mr-2' %>
          <%= link_to 'Excluir', developer, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>

<h2>Publishers</h2>

<%= link_to 'Criar novo publisher', new_publisher_path, class: 'btn btn-primary mb-3' %>

<table class="table">
  <thead class="thead-dark">
    <tr>
      <th scope="col">Nome</th>
      <th scope="col">Descrição</th>
      <th scope="col">Ação</th>
    </tr>
  </thead>

  <tbody>
    <% @publishers.each do |publisher| %>
      <tr>
        <td><%= publisher.name_publisher %></td>
        <td><%= publisher.description_publisher %></td>
        <td>
          <%= link_to 'Visualizar', publisher, class: 'btn btn-secondary mr-2' %>
          <%= link_to 'Editar', edit_publisher_path(publisher), class: 'btn btn-info mr-2' %>
          <%= link_to 'Excluir', publisher, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>

<h2>Gêneros</h2>

<%= link_to 'Criar novo gênero', new_genre_path, class: 'btn btn-primary mb-3' %>

<table class="table">
  <thead class="thead-dark">
    <tr>
      <th scope="col">Nome</th>
      <th scope="col">Descrição</th>
      <th scope="col">Ação</th>
    </tr>
  </thead>

  <tbody>
    <% @genres.each do |genre| %>
      <tr>
        <td><%= genre.name_genre %></td>
        <td><%= genre.description_genre %></td>
        <td>
          <%= link_to 'Visualizar', genre, class: 'btn btn-secondary mr-2' %>
          <%= link_to 'Editar', edit_genre_path(genre), class: 'btn btn-info mr-2' %>
          <%= link_to 'Excluir', genre, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
  <header>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <!-- Bootstrap icons-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
    <!-- Google fonts-->
    <link rel="preconnect" href="https://fonts.gstatic.com" />
    <link href="https://fonts.googleapis.com/css2?family=Newsreader:ital,wght@0,600;1,600&amp;display=swap" rel="stylesheet" />
    <link href="https://fonts.googleapis.com/css2?family=Mulish:ital,wght@0,300;0,500;0,600;0,700;1,300;1,500;1,600;1,700&amp;display=swap" rel="stylesheet" />
    <link href="https://fonts.googleapis.com/css2?family=Kanit:ital,wght@0,400;1,400&amp;display=swap" rel="stylesheet" />
    <!-- Core theme CSS (includes Bootstrap)-->
    <%= stylesheet_link_tag 'style.css' %>
  </header>
  <body id="page-top">
    
    <!-- Navigation-->
    <nav class="navbar navbar-expand-lg navbar-light fixed-top shadow-sm" id="mainNav">
      <div class="d-flex justify-content-end">
        <%= link_to root_path do %>
          <%= image_tag "logo.png", style: "border:none; max-width:60px;" %>
        <% end %>
      </div>
      <ul class="navbar-nav ms-auto me-1 my-1 my-lg-0">
        <li class="nav-item"><a class="nav-link" href="<%= games_path %>">Games</a></li>
      </ul>
      <ul class="navbar-nav ms-auto me-1 my-1 my-lg-0">
        <li class="nav-item"><a class="nav-link" href="<%= developers_path %>">Developers</a></li>
      </ul>
      <ul class="navbar-nav ms-auto me-1 my-1 my-lg-0">
        <li class="nav-item"><a class="nav-link" href="<%= genres_path %>">Genres</a></li>
      </ul>
      <ul class="navbar-nav ms-auto me-1 my-1 my-lg-0">
        <li class="nav-item"><a class="nav-link" href="<%= platforms_path %>">Platforms</a></li>
      </ul>
      <ul class="navbar-nav ms-auto me-1 my-1 my-lg-0">
        <li class="nav-item"><a class="nav-link" href="<%= promotions_path %>">Promotions</a></li>
      </ul>
      <div class="container px-5">
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ms-auto me-4 my-3 my-lg-0">
            <li class="nav-item"><a class="nav-link me-lg-3" href="<%= new_user_session_path %>">Entre</a></li>
          </ul>
          <button class="btn btn-primary rounded-pill px-3 mb-2 mb-lg-0" data-bs-toggle="modal" data-bs-target="#feedbackModal">
            <span class="d-flex align-items-center">
              <span class="small"><a href="<%= new_user_registration_path %>">Cadastre-se</a></span>
            </span>
          </button>
        </div>
      </div>
    </nav>
     <section class="content">
    <%= yield %>
  </section>
</div>
    <!-- Footer-->
    <footer class="bg-black text-center py-5">
      <div class="container px-5">
        <div class="text-white-50 small">
          <div class="mb-2">&copy; Plague.me 2023. Todos os Direitos Reservados.</div>
          <a href="#!">Privacidade</a>
          <span class="mx-1">&middot;</span>
          <a href="#!">Termos</a>
          <span class="mx-1">&middot;</span>
          <a href="#!">FAQ</a>
        </div>
      </div>
    </footer>

    <!-- * * Activate your form at https://startbootstrap.com/solution/contact-forms * *
    <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
    <script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>
  </body>
</html>