config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'

  get 'filtered_search/games', to: 'games#filtered_search', as: 'filtered_search_games'
  get 'users/:user_id/library', to: 'user_games#index', as: :user_library
  get 'user_games/:user_id/edit', to: 'user_games#edit'
  resources :promotions
  resources :games
  
  resources :platforms
  resources :developers
  resources :publishers
  resources :genres
  devise_for :users
  resources :users do
    resources :friend_requests, only: [:create, :destroy, :show] do
      member do
        put :accept
      end
    end
    member do
      get 'friends'
    end
  end
  resources :friendships, only: [:create, :destroy]
  resources :reviews
  resources :collections do
    delete 'games/:id', to: 'collections#remove_game', as: :remove_game
  end 
  resources :user_games, only: [:create, :edit, :update]
  resources :games do
    resources :user_games, only: [:create, :edit, :update]
    member do
      post 'wishlist'
      post 'favorite'
      post :add_to_collection
    end
      post 'create_review', on: :member
  end
  get 'admin', to: 'admin#index'
  namespace :admin do
    resources :users
  end
  authenticate :user, ->(user) { user.is_admin? } do
    namespace :admin do
      root to: "users#index"
    end
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/collection.rb
class Collection < ApplicationRecord
  belongs_to :user
  has_many :collection_items, dependent: :destroy
  has_many :games, through: :collection_items
end

app/models/developer.rb
class Developer < ApplicationRecord
    validates :name_developer, :description_developer, presence: true
    has_many :games
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :game
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :user
  belongs_to :friend, class_name: 'User'

  validates :friend_id, uniqueness: { scope: :user_id }

  def self.create_from_request(request)
    create(user_id: request.user_id, friend_id: request.friend_id, status: 'aceito')
  end

  def remove_friendship
    user.friends.destroy(friend)
    friend.friends.destroy(user)
    destroy
  end
  
end

app/models/game.rb
class Game < ApplicationRecord
    validates :name_game, :description_game, presence: true
    validates :rate_game, numericality: { greater_than_or_equal_to: 0.0, less_than_or_equal_to: 10.0 }
    has_one_attached :icon
    
    belongs_to :publisher
    has_and_belongs_to_many :genres, join_table: :game_genres
    accepts_nested_attributes_for :genres
    has_many :promotion_games
    has_many :promotions, through: :promotion_games
    has_and_belongs_to_many :platforms, join_table: :game_platforms
    accepts_nested_attributes_for :platforms
    belongs_to :developer
    has_many :reviews, dependent: :destroy
    has_many :favorites, dependent: :destroy
    has_many :favorited_by, through: :favorites, source: :user
    has_many :collection_items, dependent: :destroy
    has_many :collections, through: :collection_items
    has_many :wishlists, dependent: :destroy
    has_many :wishlisted_by, through: :wishlists, source: :user
    has_many :user_games, dependent: :destroy
    has_many :users, through: :user_games

    def calculate_average_rating
        reviews.average(:score).to_f.round(1)
      end
      
end

app/models/game_genre.rb
class GameGenre < ApplicationRecord
  belongs_to :game
  belongs_to :genre
end

app/models/game_platform.rb
class GamePlatform < ApplicationRecord
  belongs_to :game
  belongs_to :platform
end

app/models/genre.rb
class Genre < ApplicationRecord
    validates :name_genre, :description_genre, presence: true
    has_and_belongs_to_many :games, join_table: :game_genres
    #has_many :games, through: :game_genres
end

app/models/platform.rb
class Platform < ApplicationRecord
    validates :name_platform, :description_platform, presence: true
    has_and_belongs_to_many :games, join_table: :game_platforms
    #has_many :games, through: :game_platforms
end

app/models/promotion.rb
class Promotion < ApplicationRecord
  belongs_to :game
  has_many :promotion_games
  has_many :games, through: :promotion_games
  has_many :user_promotions
  has_many :users, through: :user_promotions
  validates :title, :description, :start_date, :end_date, presence: true
  validate :end_date_is_after_start_date

  private
  def end_date_is_after_start_date
    return if end_date.blank? || start_date.blank?

    if end_date < start_date
      errors.add(:end_date, "deve ser maior que a data inicial.")
    end
  end

end

app/models/publisher.rb
class Publisher < ApplicationRecord
    validates :name_publisher, :description_publisher, presence: true
    has_many :games
end

app/models/review.rb
class Review < ApplicationRecord
  validates :score, numericality: { greater_than_or_equal_to: 0.0, less_than_or_equal_to: 10.0 }
  validates :user_id, uniqueness: { scope: :game_id }
  belongs_to :game
  belongs_to :user
end

app/models/shop.rb
class Shop < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  validates :nickname, :description, presence: true
  has_many :user_promotions
  has_many :collections, dependent: :destroy
  has_many :promotions, through: :user_promotions
  has_many :reviews
  has_many :favorites, dependent: :destroy
  has_many :favorite_games, through: :favorites, source: :game
  has_many :wishlists, dependent: :destroy
  has_many :wishlist_games, through: :wishlists, source: :game
  has_many :user_games, dependent: :destroy
  has_many :games, through: :user_games
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  enum role: [:user, :admin]

  has_many :friendships, dependent: :destroy
  has_many :friends, through: :friendships
  has_many :inverse_friendships, class_name: 'Friendship', foreign_key: 'friend_id', dependent: :destroy
  has_many :inverse_friends, through: :inverse_friendships, source: :user    
  
  has_many :sent_friend_requests, class_name: 'FriendRequest', foreign_key: 'requester_id', dependent: :destroy
  has_many :received_friend_requests, class_name: 'FriendRequest', foreign_key: 'receiver_id', dependent: :destroy

  def friendship_with(other_user)
    Friendship.find_by(user: self, friend: other_user) || Friendship.find_by(user: other_user, friend: self)
  end
  
  def recommended_games
    friend_ids = friendships.pluck(:friend_id)
    friend_favorite_game_ids = Favorite.where(user_id: friend_ids).pluck(:game_id)
    excluded_game_ids = game_ids + favorite_games.pluck(:id)
    Game.where(id: friend_favorite_game_ids).where.not(id: excluded_game_ids + user_games.pluck(:game_id))
  end

  def is_admin?
    self.admin
  end

end

app/models/user_game.rb
class UserGame < ApplicationRecord
  validates :user, :game, presence: true
  validates :game_id, uniqueness: { scope: :user_id }
  belongs_to :user
  belongs_to :game
  enum status: [:played, :playing, :unfinished]
end

app/models/wishlist.rb
class Wishlist < ApplicationRecord
  belongs_to :user
  belongs_to :game
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def show
    @user = User.find(params[:id])
  end
  
  def update
    if current_user.update(user_params)
      redirect_to user_path(current_user), notice: 'Descrição atualizada com sucesso.'
    else
      render :edit
    end
  end

  def friends
    @user = User.find(params[:id])
    @friends = @user.friends
  end

  private

  def user_params
    params.require(:user).permit(:nickname, :description)
  end

end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/friends.html.erb
<h1>Friends</h1>
<% @friends.each do |friend| %>
<ul>
  <li><%= link_to friend.nickname, user_path(friend) %></li>
</ul>
<% end %>

<%= link_to "Back", user_path(@user), class: 'btn btn-primary' %>

app/views/users/show.html.erb
<h1>Perfil de <%= @user.nickname %></h1>
<p><%= @user.description %></p>

<h3>Favoritos</h3>
<ul>
  <% @user.favorite_games.each do |game| %>
    <li><%= link_to game.name_game, game %></li>
  <% end %>
</ul>

<h3><%= link_to "Biblioteca", user_library_path(@user), class: 'btn btn-primary' %></h3>

<h3>Wishlist</h3>
<ul>
  <% @user.wishlist_games.each do |game| %>
    <li><%= link_to game.name_game, game %></li>
  <% end %>
</ul>

<h3>Coleções </h3> 
  <% if user_signed_in? && current_user == @user %>
    <% if @user.collections.any? %>
      <%= link_to "Criar Nova", new_collection_path, class: 'btn btn-outline-success' %> 
    <% end %> 
  <% end %>
  <% if @user.collections.any? %>
    <ul>
      <% @user.collections.each do |collection| %>
        <li><%= link_to collection.title, collection_path(collection) %></li>
      <% end %>
    </ul>
  <% elsif current_user == @user %>
    <p>Você ainda não possui uma coleção. <%= link_to "Criar", new_collection_path %></p>
  <% else %>
    <p>Este usuário ainda não possui nenhuma coleção.</p>
  <% end %>

<% if user_signed_in? && current_user == @user %>
    <%= link_to 'Editar perfil', edit_user_registration_path, class: 'btn btn-primary' %>
<% end %>

<%= link_to "Amigos", friends_user_path(@user), class: 'btn btn-primary' %>

<% if current_user == @user %>
<%= link_to "Solicitações de amizade", user_friend_request_path(@user), class: 'btn btn-primary' %>
<% end %>

<% if current_user != @user %>
  <% if current_user.friends.include?(@user) %>
    <%= button_to "Desfazer amizade", friendship_path(current_user.friendship_with(@user)), method: :delete, class: 'btn btn-danger' %>
  <% elsif current_user.sent_friend_requests.exists?(receiver: @user) %>
    <%= link_to "Solicitação de amizade pendente", "#" %>
  <% else %>
    <%= button_to "Enviar solicitação de amizade", user_friend_requests_path(@user), method: :post, class: 'btn btn-primary' %>
  <% end %>
<% end %>

