config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'

  get 'filtered_search/games', to: 'games#filtered_search', as: 'filtered_search_games'
  get 'users/:user_id/library', to: 'user_games#index', as: :user_library
  get 'user_games/:user_id/edit', to: 'user_games#edit'
  resources :promotions
  resources :games
  
  resources :platforms
  resources :developers
  resources :publishers
  resources :genres
  devise_for :users
  resources :users do
    resources :friend_requests, only: [:create, :destroy, :show] do
      member do
        put :accept
      end
    end
    member do
      get 'friends'
    end
  end
  resources :friendships, only: [:create, :destroy]
  resources :reviews
  resources :collections do
    delete 'games/:id', to: 'collections#remove_game', as: :remove_game
  end 
  resources :user_games, only: [:create, :edit, :update]
  resources :games do
    resources :user_games, only: [:create, :edit, :update]
    member do
      post 'wishlist'
      post 'favorite'
      post :add_to_collection
    end
      post 'create_review', on: :member
  end
  get 'admin', to: 'admin#index'
  namespace :admin do
    resources :users
  end
  authenticate :user, ->(user) { user.is_admin? } do
    namespace :admin do
      root to: "users#index"
    end
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/game.rb
class Game < ApplicationRecord
    validates :name_game, :description_game, presence: true
    validates :rate_game, numericality: { greater_than_or_equal_to: 0.0, less_than_or_equal_to: 10.0 }
    has_one_attached :icon
    
    belongs_to :publisher
    has_and_belongs_to_many :genres, join_table: :game_genres
    accepts_nested_attributes_for :genres
    has_many :promotion_games
    has_many :promotions, through: :promotion_games
    has_and_belongs_to_many :platforms, join_table: :game_platforms
    accepts_nested_attributes_for :platforms
    belongs_to :developer
    has_many :reviews, dependent: :destroy
    has_many :favorites, dependent: :destroy
    has_many :favorited_by, through: :favorites, source: :user
    has_many :collection_items, dependent: :destroy
    has_many :collections, through: :collection_items
    has_many :wishlists, dependent: :destroy
    has_many :wishlisted_by, through: :wishlists, source: :user
    has_many :user_games, dependent: :destroy
    has_many :users, through: :user_games

    def calculate_average_rating
        reviews.average(:score).to_f.round(1)
      end
      
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, only: %i[favorite wishlist]

  # GET /games or /games.json
  def index
    if params[:query].present?
      @games = Game.where("name_game ILIKE ?", "%#{params[:query]}%")
    else
      @games = Game.all
    end
  end

  def filtered_search
    @genres = Genre.all
    @games = if params[:genre_id].present?
      Genre.find(params[:genre_id]).games
    else
      Game.all
    end
  end

  # GET /games/1 or /games/1.json
  def show
    @games = Game.find(params[:id])
    @average_rating = @game.rate_game
  end

  # GET /games/new
  def new
    @game = Game.new
    @game.genres.build
    @game.platforms.build
  end

  # GET /games/1/edit
  def edit
  end

  # POST /games or /games.json
  def create
    @game = Game.new(game_params)

    respond_to do |format|
      if @game.save
        format.html { redirect_to game_url(@game), notice: "Game was successfully created." }
        format.json { render :show, status: :created, location: @game }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /games/1 or /games/1.json
  def update
    respond_to do |format|
      if @game.update(game_params)
        format.html { redirect_to game_url(@game), notice: "Game was successfully updated." }
        format.json { render :show, status: :ok, location: @game }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1 or /games/1.json
  def destroy
    @game.destroy

    respond_to do |format|
      format.html { redirect_to games_url, notice: "Game was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def favorite
    @game = Game.find(params[:id])
    if current_user.favorite_games.delete(@game)
      flash[:notice] = "Game removed from favorites."
    else
      current_user.favorite_games << @game
      flash[:notice] = "Game added to favorites."
    end
    redirect_to @game
  end

  def wishlist
    @game = Game.find(params[:id])
    if current_user.wishlist_games.destroy(@game)
      flash[:notice] = "Game removed from wishlist."
    else
      current_user.wishlist_games << @game
      flash[:notice] = "Game added to wishlist."
    end
    redirect_to @game
  end

  def add_to_collection
    @game = Game.find(params[:id])
    @collection = current_user.collections.find(params[:collection_item][:collection_id])
    if @collection.collection_items.exists?(game_id: @game.id)
      redirect_to @game, alert: 'Este jogo já está na coleção.'
    else
      @collection_item = CollectionItem.new(collection: @collection, game: @game)
      if @collection_item.save
        redirect_to @game, notice: 'Jogo adicionado à coleção.'
      else
        redirect_to @game, alert: 'Falha ao adicionar jogo à coleção.'
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game
      @game = Game.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def game_params
      params.require(:game).permit(:name_game, :description_game, :release, :rate_game, :franchise, :publisher_id, :developer_id, :icon, genre_ids: [], platform_ids: [])
    end

end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/_form.html.erb

<%= simple_form_for(@game) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.file_field :icon %>
    <%= f.input :name_game %>
    <%= f.input :description_game %>
    <%= f.input :release %>
    <%= f.input :rate_game, input_html: { value: @average_rating } %>
    <%= f.input :franchise %>
    <%= f.label :genres %>
    <%= f.collection_check_boxes :genre_ids, Genre.all, :id, :name_genre %>
    <br>
    <%= f.label :platforms %>
    <%= f.collection_check_boxes :platform_ids, Platform.all, :id, :name_platform %>
    <br>
    <%= f.label :publisher %>
    <%= f.collection_select :publisher_id, Publisher.all, :id, :name_publisher %>
    <br>
    <%= f.label :developer %>
    <%= f.collection_select :developer_id, Developer.all, :id, :name_developer %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/games/_game.html.erb
<div id="<%= dom_id game %>">

  <p>
    <strong>Name game:</strong>
    <%= game.name_game %>
  </p>

  <p>
    <strong>Description game:</strong>
    <%= game.description_game %>
  </p>

  <p>
    <strong>Release:</strong>
    <%= game.release %>
  </p>

  <p>
    <strong>Rate game:</strong>
    <% if game.reviews.any?%>
      <%= game.rate_game %>
    <% else %>
      <p>Seja o primeiro a avaliar esse jogo!</p>
    <% end %>
  </p>

  <p>
    <strong>Franchise:</strong>
    <%= game.franchise %>
  </p>

  <p>
    <strong>Publisher:</strong>
    <%= link_to game.publisher.name_publisher, publisher_path(game.publisher.id) %>
  </p>

  <p>
    <strong>Developer:</strong>
    <%= link_to game.developer.name_developer, developer_path(game.developer.id) %>
  </p>

  <p>
    <strong>Genres:</strong>
    <% game.genres.each do |genre| %>
      <%= link_to genre.name_genre, filtered_search_games_path(genre_id: genre.id) %>
    <% end %>
  </p>

  <p>
    <strong>Platforms:</strong>
    <% game.platforms.each do |platform| %>
      <%= link_to platform.name_platform, platform_path(platform.id) %>
    <% end %>
  
</div>

app/views/games/edit.html.erb
<h1>Editing game</h1>

<%= render "form", game: @game %>

<br>

<div>
  <%= link_to "Show this game", @game %> |
  <%= link_to "Back to games", games_path %>
</div>

app/views/games/filtered_search.html.erb
<h1>Filtered Games</h1>

<%= form_tag filtered_search_games_path, method: :get do %>
  <%= label_tag :genre_id, "Filter by genre:" %>
  <%= select_tag :genre_id, options_from_collection_for_select(@genres, :id, :name_genre) %>
  <%= submit_tag "Filter" %>
<% end %>

<% @games.each do |game| %>
  <p><%= link_to game.name_game, game_path(game) %></p>
<% end %>

app/views/games/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Games</h1>

<div id="games">
  <% @games.each do |game| %>
    <p><%= link_to game.name_game, game %></p>
  <% end %>
</div>

<%= link_to "Filtered Search", filtered_search_games_path %>


app/views/games/new.html.erb
<h1>New game</h1>

<%= render "form", game: @game %>

<br>

<div>
  <%= link_to "Back to games", games_path %>
</div>

app/views/games/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @game %>

<h2>Reviews:</h2>

<% @game.reviews.each do |review| %>
  <p><%= link_to "#{review.user.nickname}:", user_path(review.user) %></p>
  <p><%= review.content %> - Nota: <%= review.score %> - Postado em <%= review.posted_at.strftime('%d/%m/%Y %H:%M:%S') %>
  <% if review.user == current_user %>
  <%= button_to 'Excluir', review_path(review), method: :delete %></p>
<% end %>
<% end %>

<h2>Deixe sua review:</h2>

<form action="<%= reviews_path(@game) %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <input type="hidden" name="game_id" value="<%= @game.id %>">
  <textarea name="review[content]"></textarea>
  <label for="score">Nota:</label>
  <input type="number" name="review[score]" min="0" max="10" step="0.1">
  <input type="submit" value="Postar review">
</form>

<div>

<br>

<% if user_signed_in? %>
  <% if current_user.favorite_games.include?(@game) %>
    <%= button_to 'Remover dos favoritos', favorite_game_path(@game), method: :post, class: 'btn btn-outline-danger' %>
  <% else %>
    <%= button_to 'Adicionar aos favoritos', favorite_game_path(@game), method: :post, class: 'btn btn-outline-success' %>
  <% end %>

<%= form_for current_user.user_games.build(game_id: @game.id), url: game_user_games_path(@game) do |f| %>
  <div class="form-group">
    <%= f.label :status %><br>
    <%= f.select :status, UserGame.statuses.keys.to_a %>
  </div>
  <%= f.submit "Adicionar à Biblioteca", class: "btn btn-primary" %>
<% end %>

   <% if current_user.wishlist_games.include?(@game) %>
    <%= button_to 'Remover da lista de desejos', wishlist_game_path(@game), method: :post, class: 'btn btn-outline-danger' %>
  <% else %>
    <%= button_to 'Adicionar à lista de desejos', wishlist_game_path(@game), method: :post, class: 'btn btn-outline-success' %>
  <% end %>

  <br>

  <%= form_tag(add_to_collection_game_path(@game), method: :post) do %>
    <%= collection_select :collection_item, :collection_id, current_user.collections, :id, :title, { prompt: 'Selecione uma coleção' } %>
    <%= submit_tag 'Adicionar à coleção' %>
  <% end %>
<% end %>

</div>